### ISSUE TITLE
Skeleton loading

### ISSUE THREAD

**Issue by Ionys320** [marcelgarus/cached_listview#2]
Hi !
When there is no data in cache and when the listview is refreshing, could you display a skeleton text loading with the package https://pub.dev/packages/skeleton_text ?

**Comment by MarcelGarus** [comment]
Sorry for the late answer.
Not sure that applies here, because the package only provides a very rough framework for showing content. The content itself (the loading screen etc) still has to be designed by you.
So developers are free to display whatever they like.
