### ISSUE TITLE
Can't refresh data

### ISSUE THREAD

**Issue by Nico04** [marcelgarus/cached_listview#4]
Using your exemple project, on the CacheBuilder page, using pull-to-refresh OR calling directly controller.fetch() doesn't refresh the data, controller's fetcher function is only call the first time.

**Comment by Nico04** [comment]
Maybe it's coming from your Batcher class, line 7 : 
`_currentFetcher ??= callback();`
That means that `callblack()` is only called if `_currentFetcher` is null, which is only the first time.

**Comment by MarcelGarus** [comment]
Oh, very true.
I'm on it.

**Comment by MarcelGarus** [comment]
Okay, a version 4.2.5 has just been `pub lish`ed and fixes this error.
Thanks for spotting it! 😊

**Comment by Nico04** [comment]
Works great, thank you for your responsiveness 👍  !
